# Build stage
FROM node:16-alpine as build

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install @react-navigation/stack@6.3.20 react-native-gesture-handler@~2.9.0 --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Build the Expo web app
RUN npx expo export:web

# Production stage
FROM nginx:alpine

# Copy the built web app from the build stage
COPY --from=build /app/web-build /usr/share/nginx/html

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
